name: "Check amalgamation"

on:
  pull_request:

permissions: read-all

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/number
          echo ${{ github.event.pull_request.user.login }} > ./pr/author
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/

  check:
    runs-on: ubuntu-latest
    container: silkeh/clang:dev
    env:
      MAIN_DIR: ${{ github.workspace }}/main

    steps:
      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          path: main
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout tools
        uses: actions/checkout@v3
        with:
          path: tools
          ref: develop

      - name: Check amalgamation
        run: |
          cd $MAIN_DIR
          make check-amalgamation
